version: '3.3'

services:
  project-db:
    container_name: project-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGPASSWORD: admin
    build:
      context: ./services/db
    ports:
      - '5432:5432'
    networks:
      - 'backend-net'


  project-api:
    container_name: project-api
    build:
      context: ./services/api
    ports:
      - '9001:9001'
    volumes:
      - './services/api:/src/api'
      - '/src/api/node_modules'
    environment:
      NODE_ENV: 'dev'
      port: '9001'
      BABEL_DISABLE_CACHE: 1
      JWT_SECRET: 'H34e626&D7'
      JWT_COOKIE_NAME: 'project-starter-dev-token'
      DATABASE_URL: 'postgres://admin:admin@project-db:5432/project'
      DATABASE_TEST_URL: 'postgres://admin:admin@project-db:5432/project-integration'
    networks:
      - 'backend-net'
      - 'frontend-net'

  project-web:
    container_name: project-web
    build:
      context: ./web
    ports:
      - '3000:3000'
      - '35729:35729'
    environment:
      NODE_ENV: 'development'
      CHOKIDAR_USEPOLLING: 1
      JWT_SECRET: 'H34e626&D7'
      JWT_COOKIE_NAME: 'project-token'
    volumes:
      - './web:/src/app'
      - '/src/app/node_modules'
    depends_on:
      - 'project-db'
      - 'project-api'
    networks:
      - 'frontend-net'

networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge
